module.exports = {
  NEW_ROOM: "room:new",
  JOIN_ROOM: "room:join",
  ROOM_CONNECTED: "room:connected",
  ROOM_SELECT_ANIME: "room:select_anime",
  ROOM_SET_ANIME: "room:set_anime",
  ROOM_SELECT_EPISODE: "room:select_episode",
  ROOM_GETTING_EPISODE_STATUS: "room:getting_episode_status",
  ROOM_SET_EPISODE: "room:set_episode",
  ROOM_REQUEST_CHANGE_PLAYING_STATUS: "room:request_change_playing_status",
  ROOM_CHANGE_PLAYING_STATUS: "room:toggle_play",
  ROOM_SET_CURRENT_TIME: "room:set_current_time",
  ROOM_REQUEST_CHANGE_CURRENT_TIME: "room:request_change_current_time",
  ROOM_CHANGE_CURRENT_TIME: "room:request_change_current_time",
};
